name: test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
      - name: Set up Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: "npm"
      - name: Install dependencies
        run: npm ci
      - name: Run Prettier, ESLint, and unit tests
        run: npm test
  release:
    needs: test
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    env:
      HUSKY: 0
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
      - name: Set up Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: "npm"
      - name: Install dependencies
        run: npm ci
      - name: Publish to NPM
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
